name: Run Cypress Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Pobierz kod
        uses: actions/checkout@v4

      - name: ğŸ—ï¸ Skonfiguruj Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: ğŸ§ª Uruchom testy Cypress
        uses: cypress-io/github-action@v6
        with:
          install: false
          command: yarn test:cypress

      - name: ğŸ“‚ PrzeÅ›lij zrzuty ekranu (jeÅ›li testy siÄ™ nie powiodÄ…)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: __tests__/report/screenshots

      - name: ğŸ“‚ PrzeÅ›lij nagrania testÃ³w (jeÅ›li sÄ… wÅ‚Ä…czone)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
